#lang sicp

(#%require "type.rkt")
(#%require "table.rkt")
(#%require "generic.rkt")

(#%provide make-real)

(define (install-real-package)
  (define (tag x)
    (attach-tag 'real x))
  (put 'add '(real real)
       (lambda (x y) (tag (+ x y))))
  (put 'sub '(real real)
       (lambda (x y) (tag (- x y))))
  (put 'mul '(real real)
       (lambda (x y) (tag (* x y))))
  (put 'div '(real real)
       (lambda (x y) (tag (/ x y))))
  (put 'addd '(real real real)
       (lambda (x y z) (tag (+ x y z))))
  (put 'equ? '(real real)
       (lambda (x y)
         (= x y)))
  (put '=zero? '(real)
       (lambda (x)
         (= x 0.0)))
  (put 'negative '(real)
       (lambda (x)
         (tag(- x))))

  (put 'make 'real
       (lambda (x)
          (if (exact? x)
              (tag (exact->inexact x))
              (tag x))))
  'done)

(install-real-package)
(define (make-real n)
  ((get 'make 'real) n))
